service: flask-app

provider:
  name: aws
  runtime: python3.12.4
  region: ap-south-1

plugins:
  - serverless-wsgi
  - serverless-python-requirements

custom:
  wsgi:
    app: app.app  # Adjust this to match your Flask app's entry point
    packRequirements: true

package:
  exclude:
    - venv/**
    - .git/**
    - node_modules/**
    - typing_extensions.py
functions:
  app:
    handler: wsgi.handler
    events:
      - http: ANY /
      - http: ANY /{proxy+}



